import RainbowKitAndChakraProvider from "./RainbowKitAndChakraProvider";
import Layout from "@/components/Layout";
import { ReactNode } from 'react';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <RainbowKitAndChakraProvider>
      <Layout>
        {children}
      </Layout>
    </RainbowKitAndChakraProvider>
  );
}
